Repository jquery/jquery-ui, pull requests merged in 2022-07, with the labels that each got.

#2067 Datepicker: Capitalize some Indonesian words
  ui/i18n/datepicker-id.js
Labels: Bug, Localization

#2102 Checkboxradio: Don't re-evaluate text labels as HTML
  tests/unit/checkboxradio/checkboxradio.html
  tests/unit/checkboxradio/core.js
  tests/unit/checkboxradio/methods.js
  ui/widgets/checkboxradio.js
Labels: Bug, Comp: Checkboxradio

#2103 Docs: Add a security policy in SECURITY.md
  SECURITY.md
Labels: Comp: Docs
