Repository jquery/jquery-ui, pull requests merged in 2024-05, with the labels that each got.

#2250 Core: Make back compat disabled by default
  tests/lib/bootstrap.js
  tests/unit/button/button.html
  tests/unit/dialog/dialog.html
  tests/unit/droppable/droppable.html
  tests/unit/tabs/core.js
  tests/unit/tooltip/tooltip.html
  ui/effect.js
  ui/effects/effect-transfer.js
  ui/widgets/button.js
  ui/widgets/dialog.js
  ui/widgets/droppable.js
  ui/widgets/resizable.js
  ui/widgets/spinner.js
  ui/widgets/tabs.js
  ui/widgets/tooltip.js
Labels: Comp: Core, Needs review

#2251 Tests: remove code supporting jenkins and testswarm
  Gruntfile.js
  package.json
  tests/lib/bootstrap.js
  tests/unit/draggable/options.js
Labels: Comp: Build

#2254 Build: Report compressed sizes in compare_size
  Gruntfile.js
Labels: Comp: Build, Needs review

#2248 Build: Report compressed sizes in compare_size
  Gruntfile.js
Labels: Comp: Build
